import Link from 'next/link'
import { Plus } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Header } from '@/components/layout/header'
import { Footer } from '@/components/layout/footer'
import { BusinessFilters } from '@/components/businesses/business-filters'
import { Business } from '@/types/business'

// Real Oromo/Ethiopian businesses in Minnesota
const realBusinesses: Business[] = [
  // FEATURED PARTNERS (from homepage)
  {
    id: 'featured-1',
    name: 'Adama Restaurant',
    slug: 'adama-restaurant',
    description: 'Family-owned restaurant offering sophisticated Oromo, Ethiopian and East African cuisine. Named after the second largest city in Oromia. Fresh injera baked daily, catering available for all occasions.',
    category: 'restaurant-food',
    address: '3970 Central Ave NE',
    city: 'Columbia Heights',
    state: 'MN',
    zip_code: '55421',
    phone: '(763) 789-4485',
    email: 'info@adamarestaurantmn.com',
    website: 'https://adamarestaurantmn.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '21:00' },
      tuesday: { open: '11:00', close: '21:00' },
      wednesday: { open: '11:00', close: '21:00' },
      thursday: { open: '11:00', close: '21:00' },
      friday: { open: '11:00', close: '21:00' },
      saturday: { open: '11:00', close: '21:00' },
      sunday: { open: '11:00', close: '21:00' },
    },
    rating: 4.8,
    review_count: 142,
    is_verified: true,
    is_claimed: true,
    is_featured: true,
    owner_id: 'featured-1',
    status: 'approved',
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'featured-2',
    name: 'Oromo Community of Minnesota',
    slug: 'oromo-community-minnesota',
    description: 'The first African immigrant community to fully own a community building in Minnesota. Providing social services, employment assistance, health education, elderly programs, youth and cultural programs since 1985.',
    category: 'religious-community',
    address: '465 N Mackubin St',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55103',
    phone: '(651) 757-3040',
    email: 'info@oromocommunitymn.org',
    website: 'https://oromocommunitymn.org/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: '10:00', close: '14:00' },
      sunday: null,
    },
    rating: 4.9,
    review_count: 89,
    is_verified: true,
    is_claimed: true,
    is_featured: true,
    owner_id: 'featured-2',
    status: 'approved',
    created_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'featured-3',
    name: 'Oromo Resource Center of Minnesota',
    slug: 'oromo-resource-center',
    description: 'Established in 2020 to meet the various needs of the Oromo & East African Community. Offering family services, healthcare applications, housing resources, immigration assistance, food assistance, and elder support.',
    category: 'professional-services',
    address: '1821 University Ave W',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55104',
    phone: '(651) 300-4567',
    email: 'info@oromoresourcecenter.org',
    website: 'https://www.oromoresourcecenter.org/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: null,
      sunday: null,
    },
    rating: 4.9,
    review_count: 67,
    is_verified: true,
    is_claimed: true,
    is_featured: true,
    owner_id: 'featured-3',
    status: 'approved',
    created_at: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // RESTAURANTS
  {
    id: '1',
    name: 'Katar River Ethiopian Restaurant & Bakery',
    slug: 'katar-river-restaurant',
    description: 'Traditional Ethiopian restaurant known for having the best injera in town. Delivering hundreds of orders to ethnic restaurants and grocery stores throughout the metro. Open since 2008.',
    category: 'restaurant-food',
    address: '2751 Minnehaha Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55406',
    phone: '(612) 245-0556',
    email: 'info@katarrestaurant.com',
    website: 'https://katarrestaurant.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '10:00', close: '22:00' },
      tuesday: { open: '10:00', close: '22:00' },
      wednesday: { open: '10:00', close: '22:00' },
      thursday: { open: '10:00', close: '22:00' },
      friday: { open: '10:00', close: '22:00' },
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    rating: 4.7,
    review_count: 156,
    is_verified: true,
    is_claimed: true,
    owner_id: '1',
    status: 'approved',
    created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: "Dilla's Ethiopian Restaurant",
    slug: 'dillas-ethiopian-restaurant',
    description: 'Authentic Ethiopian cuisine in the heart of Cedar-Riverside. Extensive menu of traditional and specialty dishes. Combo platters and buffet available. Open 7 days a week.',
    category: 'restaurant-food',
    address: '1813 Riverside Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 332-2898',
    email: 'info@dillasethiopianmn.com',
    website: 'https://dillasethiopianmn.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '02:00' },
      tuesday: { open: '11:00', close: '02:00' },
      wednesday: { open: '11:00', close: '02:00' },
      thursday: { open: '11:00', close: '02:00' },
      friday: { open: '11:00', close: '02:00' },
      saturday: { open: '11:00', close: '02:00' },
      sunday: { open: '11:00', close: '02:00' },
    },
    rating: 4.6,
    review_count: 168,
    is_verified: true,
    is_claimed: true,
    owner_id: '2',
    status: 'approved',
    created_at: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'The Red Sea Ethiopian Restaurant',
    slug: 'red-sea-ethiopian',
    description: "Minneapolis' first Ethiopian Restaurant since 1990. Authentic Ethiopian & Eritrean food with vegetarian options. Full bar with daily Happy Hour from 4-9pm.",
    category: 'restaurant-food',
    address: '320 Cedar Ave S',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 333-1644',
    email: 'info@theredseampls.com',
    website: 'https://theredseampls.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '23:00' },
      tuesday: { open: '11:00', close: '23:00' },
      wednesday: { open: '11:00', close: '23:00' },
      thursday: { open: '11:00', close: '23:00' },
      friday: { open: '11:00', close: '00:00' },
      saturday: { open: '11:00', close: '00:00' },
      sunday: { open: '11:00', close: '23:00' },
    },
    rating: 4.5,
    review_count: 154,
    is_verified: true,
    is_claimed: true,
    owner_id: '3',
    status: 'approved',
    created_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Bole Ethiopian Cuisine',
    slug: 'bole-ethiopian-cuisine',
    description: 'Named after the neighborhood in Addis Ababa. Authentic Ethiopian cuisine near Como Park Zoo. Reservations available, vegan options, delivery and takeout.',
    category: 'restaurant-food',
    address: '1341 Pascal St',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55108',
    phone: '(651) 330-2492',
    email: 'info@boleethiopiancuisine.com',
    website: 'https://boleethiopiancuisine.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: null,
      tuesday: { open: '11:00', close: '21:30' },
      wednesday: { open: '11:00', close: '21:30' },
      thursday: { open: '11:00', close: '21:30' },
      friday: { open: '10:00', close: '21:30' },
      saturday: { open: '10:00', close: '21:30' },
      sunday: { open: '10:00', close: '21:30' },
    },
    rating: 4.7,
    review_count: 192,
    is_verified: true,
    is_claimed: true,
    owner_id: '4',
    status: 'approved',
    created_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Selam Restaurant',
    slug: 'selam-restaurant',
    description: 'Small family-owned Ethiopian and Eritrean restaurant in South Minneapolis. Flavorful dishes showcasing regional spices, herbs, and cooking techniques. Owned by Belai Mergia and Rahel Tassew.',
    category: 'restaurant-food',
    address: '3860 Minnehaha Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55406',
    phone: '(612) 900-0815',
    email: 'info@selamrestaurantmn.com',
    website: 'https://selamrestaurantmn.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '21:00' },
      tuesday: { open: '11:00', close: '21:00' },
      wednesday: { open: '11:00', close: '21:00' },
      thursday: { open: '11:00', close: '21:00' },
      friday: { open: '11:00', close: '22:00' },
      saturday: { open: '11:00', close: '22:00' },
      sunday: { open: '11:00', close: '21:00' },
    },
    rating: 4.6,
    review_count: 78,
    is_verified: true,
    is_claimed: true,
    owner_id: '5',
    status: 'approved',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Jegol Ethiopian Kitchen',
    slug: 'jegol-ethiopian-kitchen',
    description: 'Located in the heart of Frogtown, Saint Paul. Diverse menu ranging from traditional Ethiopian dishes to Mediterranean-inspired flavors. Suitable for vegans and meat lovers.',
    category: 'restaurant-food',
    address: '691 Dale St N',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55103',
    phone: '(651) 200-3191',
    email: 'info@jegolrestaurant.com',
    website: 'https://jegolrestaurant.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '12:00', close: '20:00' },
      tuesday: { open: '12:00', close: '20:00' },
      wednesday: { open: '12:00', close: '20:00' },
      thursday: { open: '12:00', close: '20:00' },
      friday: { open: '12:00', close: '20:00' },
      saturday: { open: '12:00', close: '20:00' },
      sunday: { open: '12:00', close: '20:00' },
    },
    rating: 4.5,
    review_count: 67,
    is_verified: true,
    is_claimed: true,
    owner_id: '6',
    status: 'approved',
    created_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Demera Ethiopian Restaurant',
    slug: 'demera-ethiopian',
    description: 'Rich and vibrant flavors of Ethiopian cuisine in the heart of Saint Paul. Extensive menu showcasing the diversity and richness of Ethiopian cuisine. Take out and online ordering available.',
    category: 'restaurant-food',
    address: '823 University Ave W',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55104',
    phone: '(651) 224-6224',
    email: 'info@demeraethiopianmn.com',
    website: 'https://demeraethiopianmn.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '22:00' },
      tuesday: { open: '11:00', close: '22:00' },
      wednesday: { open: '11:00', close: '22:00' },
      thursday: { open: '11:00', close: '22:00' },
      friday: { open: '11:00', close: '22:00' },
      saturday: { open: '11:00', close: '22:00' },
      sunday: { open: '11:00', close: '22:00' },
    },
    rating: 4.6,
    review_count: 98,
    is_verified: true,
    is_claimed: true,
    owner_id: '7',
    status: 'approved',
    created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Erta Ale Ethiopian Restaurant & Bar',
    slug: 'erta-ale-ethiopian',
    description: 'Culture-oriented food business offering genuine Ethiopian cuisine alongside full bar service. Located in Lowertown, a baseball throw away from CHS Field.',
    category: 'restaurant-food',
    address: '308 E Prince St, Ste 140',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55101',
    phone: '(651) 728-8182',
    email: 'info@ertaaleethiopian.com',
    website: 'https://ertaaleethiopian.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '21:00' },
      tuesday: null,
      wednesday: { open: '11:00', close: '21:00' },
      thursday: { open: '11:00', close: '21:00' },
      friday: { open: '11:00', close: '01:00' },
      saturday: { open: '11:00', close: '01:00' },
      sunday: { open: '11:00', close: '21:00' },
    },
    rating: 4.5,
    review_count: 42,
    is_verified: true,
    is_claimed: true,
    owner_id: '8',
    status: 'approved',
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Mesob Ethiopian Restaurant',
    slug: 'mesob-ethiopian',
    description: 'Family restaurant serving authentic Ethiopian food buffets and menu orders since 2018. Black-owned by Munaye Tesfaye & Ade Terefe. Dine in or takeout available.',
    category: 'restaurant-food',
    address: '3915 Hiawatha Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55406',
    phone: '(612) 839-5868',
    email: 'mesob3915@gmail.com',
    website: 'https://mesobmn.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '22:00' },
      tuesday: { open: '11:00', close: '22:00' },
      wednesday: { open: '11:00', close: '22:00' },
      thursday: { open: '11:00', close: '22:00' },
      friday: { open: '11:00', close: '22:00' },
      saturday: { open: '11:00', close: '22:00' },
      sunday: { open: '11:00', close: '22:00' },
    },
    rating: 4.6,
    review_count: 78,
    is_verified: true,
    is_claimed: true,
    owner_id: '9',
    status: 'approved',
    created_at: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Agelgil Ethiopian Restaurant',
    slug: 'agelgil-ethiopian',
    description: 'Authentic Ethiopian cuisine in Saint Paul. Open daily serving traditional dishes with vegetarian options. Delivery and takeout available.',
    category: 'restaurant-food',
    address: '2585 7th St W',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55116',
    phone: '(651) 340-3291',
    email: 'info@agelgilmn.com',
    website: 'https://agelgilmn.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '00:00' },
      tuesday: { open: '09:00', close: '00:00' },
      wednesday: { open: '09:00', close: '00:00' },
      thursday: { open: '09:00', close: '00:00' },
      friday: { open: '09:00', close: '00:00' },
      saturday: { open: '09:00', close: '00:00' },
      sunday: { open: '09:00', close: '00:00' },
    },
    rating: 4.4,
    review_count: 55,
    is_verified: true,
    is_claimed: true,
    owner_id: '10',
    status: 'approved',
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // GROCERY & MARKETS
  {
    id: '11',
    name: 'Shabelle Grocery',
    slug: 'shabelle-grocery',
    description: 'Ethiopian grocery store and restaurant on Franklin Avenue. Complete stock of East African spices, flours, and ingredients. Green coffee beans, roasters, and traditional coffee ceremony supplies.',
    category: 'grocery-market',
    address: '2325 E Franklin Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55406',
    phone: '(612) 333-5005',
    email: 'info@shabellegrocery.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '20:00' },
      tuesday: { open: '09:00', close: '20:00' },
      wednesday: { open: '09:00', close: '20:00' },
      thursday: { open: '09:00', close: '20:00' },
      friday: { open: '09:00', close: '20:00' },
      saturday: { open: '09:00', close: '20:00' },
      sunday: { open: '09:00', close: '20:00' },
    },
    rating: 4.5,
    review_count: 89,
    is_verified: true,
    is_claimed: true,
    owner_id: '11',
    status: 'approved',
    created_at: new Date(Date.now() - 250 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: "Lucy's Market & Carryout",
    slug: 'lucys-market-carryout',
    description: 'Family-owned Ethiopian restaurant and small market. Ethiopian classic and exotic dishes plus groceries. Cooking lessons available for injera and traditional dishes. Owned by Aster Andualem.',
    category: 'grocery-market',
    address: '3749 Cedar Ave S',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55407',
    phone: '(612) 886-3748',
    email: 'aster@lucymarket.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: null,
      tuesday: null,
      wednesday: null,
      thursday: null,
      friday: null,
      saturday: { open: '11:00', close: '20:00' },
      sunday: { open: '11:00', close: '20:00' },
    },
    rating: 4.8,
    review_count: 67,
    is_verified: true,
    is_claimed: true,
    owner_id: '12',
    status: 'approved',
    created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'East African Injera Bakery',
    slug: 'east-african-injera',
    description: 'Wholesale bakery producing injera and hambasha. Custom injera-making machine creates bread with beautiful cell structure. Products available at Holy Land, Seward Co-op, and Afrik Grocery.',
    category: 'grocery-market',
    address: '786 University Ave W',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55104',
    phone: '(651) 644-5678',
    email: 'orders@eastafricaninjera.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '08:00', close: '17:00' },
      tuesday: { open: '08:00', close: '17:00' },
      wednesday: { open: '08:00', close: '17:00' },
      thursday: { open: '08:00', close: '17:00' },
      friday: { open: '08:00', close: '17:00' },
      saturday: { open: '09:00', close: '15:00' },
      sunday: null,
    },
    rating: 4.7,
    review_count: 45,
    is_verified: true,
    is_claimed: true,
    owner_id: '13',
    status: 'approved',
    created_at: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '14',
    name: "Mamas Market & Deli",
    slug: 'mamas-market-deli',
    description: 'Owned by nine Ethiopian immigrant moms. Traditional Ethiopian coffee ceremonies every Sunday after 2pm. Open 7 days a week serving the community with love.',
    category: 'grocery-market',
    address: '678 Snelling Ave N',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55104',
    phone: '(651) 489-1234',
    email: 'info@mamasmarket.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '21:00' },
      tuesday: { open: '09:00', close: '21:00' },
      wednesday: { open: '09:00', close: '21:00' },
      thursday: { open: '09:00', close: '21:00' },
      friday: { open: '09:00', close: '21:00' },
      saturday: { open: '09:00', close: '21:00' },
      sunday: { open: '09:00', close: '21:00' },
    },
    rating: 4.6,
    review_count: 34,
    is_verified: true,
    is_claimed: true,
    owner_id: '14',
    status: 'approved',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '15',
    name: 'Habeshawi Store',
    slug: 'habeshawi-store',
    description: 'The most authentic Ethiopian store for all your cultural needs. E-commerce business serving Ethiopians looking to connect with their culture and roots. Aesthetic and couture items available.',
    category: 'retail-shopping',
    address: '2200 E Lake St',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55407',
    phone: '(612) 555-0178',
    email: 'info@habeshawistore.com',
    website: 'https://habeshawistore.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '10:00', close: '19:00' },
      tuesday: { open: '10:00', close: '19:00' },
      wednesday: { open: '10:00', close: '19:00' },
      thursday: { open: '10:00', close: '19:00' },
      friday: { open: '10:00', close: '20:00' },
      saturday: { open: '10:00', close: '20:00' },
      sunday: { open: '12:00', close: '18:00' },
    },
    rating: 4.8,
    review_count: 56,
    is_verified: true,
    is_claimed: true,
    owner_id: '15',
    status: 'approved',
    created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // BEAUTY & HAIR SALONS
  {
    id: '16',
    name: 'Aziti Hair Braiding & Extensions',
    slug: 'aziti-hair-braiding',
    description: 'Professional hair braiding by Azeb Kassa with over 15 years experience. Trained in Africa, licensed by MN Board of Cosmetology. One of the best braiders in the Twin Cities.',
    category: 'beauty-personal-care',
    address: '2716 E Lake St',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55406',
    phone: '(612) 750-8923',
    email: 'info@azitihairbraiding.com',
    website: 'https://azitihairbraiding.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '19:00' },
      tuesday: { open: '09:00', close: '19:00' },
      wednesday: { open: '09:00', close: '19:00' },
      thursday: { open: '09:00', close: '19:00' },
      friday: { open: '09:00', close: '19:00' },
      saturday: { open: '09:00', close: '18:00' },
      sunday: null,
    },
    rating: 4.9,
    review_count: 134,
    is_verified: true,
    is_claimed: true,
    owner_id: '16',
    status: 'approved',
    created_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '17',
    name: 'Blue Nile Hair Braiding',
    slug: 'blue-nile-hair-braiding',
    description: 'Hair braiding salon in the vibrant Midway area of Saint Paul. Just steps from the Green Line, easily accessible for everyone. Professional braiding services.',
    category: 'beauty-personal-care',
    address: '1564 University Ave W',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55104',
    phone: '(651) 645-8900',
    email: 'info@bluenilebraiding.com',
    website: 'https://bluenilebraiding.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '18:00' },
      saturday: { open: '09:00', close: '17:00' },
      sunday: null,
    },
    rating: 4.6,
    review_count: 78,
    is_verified: true,
    is_claimed: true,
    owner_id: '17',
    status: 'approved',
    created_at: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '18',
    name: 'EDL Braiding Salon',
    slug: 'edl-braiding-salon',
    description: 'Ethiopian-American owned salon with over 8 years of experience. EDL has become a trusted name in the art of braiding, known for precision, creativity, and dedication.',
    category: 'beauty-personal-care',
    address: '3400 Nicollet Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55408',
    phone: '(612) 345-6789',
    email: 'info@edlbraiding.com',
    website: 'https://edlbraiding.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '19:00' },
      saturday: { open: '09:00', close: '17:00' },
      sunday: null,
    },
    rating: 4.8,
    review_count: 92,
    is_verified: true,
    is_claimed: true,
    owner_id: '18',
    status: 'approved',
    created_at: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // COFFEE SHOPS
  {
    id: '19',
    name: 'Sainaa Cafe',
    slug: 'sainaa-cafe',
    description: '"Sainaa" means "come inside" and "memories" in Oromo. Experience meaningful Ethiopian communal bonding through coffee. Traditional coffee ceremonies and pastries.',
    category: 'restaurant-food',
    address: '317 W Lake St',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55408',
    phone: '(612) 555-0234',
    email: 'hello@sainaacafe.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '07:00', close: '18:00' },
      tuesday: { open: '07:00', close: '18:00' },
      wednesday: { open: '07:00', close: '18:00' },
      thursday: { open: '07:00', close: '18:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '08:00', close: '19:00' },
      sunday: { open: '08:00', close: '17:00' },
    },
    rating: 4.7,
    review_count: 56,
    is_verified: true,
    is_claimed: true,
    owner_id: '19',
    status: 'approved',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '20',
    name: 'Snelling Cafe',
    slug: 'snelling-cafe',
    description: 'Hamline-Midway staple since 2003. East African, Mediterranean and American cuisines. Roasts own coffee beans on-site. Eritrean and Ethiopian flavors.',
    category: 'restaurant-food',
    address: '638 Snelling Ave N',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55104',
    phone: '(651) 644-2345',
    email: 'info@snellingcafe.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '07:00', close: '20:00' },
      tuesday: { open: '07:00', close: '20:00' },
      wednesday: { open: '07:00', close: '20:00' },
      thursday: { open: '07:00', close: '20:00' },
      friday: { open: '07:00', close: '21:00' },
      saturday: { open: '08:00', close: '21:00' },
      sunday: { open: '08:00', close: '18:00' },
    },
    rating: 4.5,
    review_count: 123,
    is_verified: true,
    is_claimed: true,
    owner_id: '20',
    status: 'approved',
    created_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // CLOTHING & FASHION
  {
    id: '21',
    name: "Safiya's Clothing",
    slug: 'safiyas-clothing',
    description: 'Wonderful blend of Oromo traditions and Muslim attire. Authentic Oromo traditional clothes from Arsii, Bale, Jimma, Hararge and more. Shipping available nationwide.',
    category: 'retail-shopping',
    address: '1890 University Ave W',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55104',
    phone: '(651) 555-0456',
    email: 'info@safiyasclothing.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '10:00', close: '18:00' },
      tuesday: { open: '10:00', close: '18:00' },
      wednesday: { open: '10:00', close: '18:00' },
      thursday: { open: '10:00', close: '18:00' },
      friday: { open: '10:00', close: '19:00' },
      saturday: { open: '10:00', close: '19:00' },
      sunday: { open: '12:00', close: '17:00' },
    },
    rating: 4.8,
    review_count: 67,
    is_verified: true,
    is_claimed: true,
    owner_id: '21',
    status: 'approved',
    created_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22',
    name: 'African Market',
    slug: 'african-market-nicollet',
    description: 'African clothing, fabrics, jewelry, and accessories. Wide selection of traditional and modern African fashion. Located on historic Nicollet Avenue.',
    category: 'retail-shopping',
    address: '1823 Nicollet Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55403',
    phone: '(612) 872-1011',
    email: 'info@africanmarketmpls.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '10:00', close: '19:00' },
      tuesday: { open: '10:00', close: '19:00' },
      wednesday: { open: '10:00', close: '19:00' },
      thursday: { open: '10:00', close: '19:00' },
      friday: { open: '10:00', close: '20:00' },
      saturday: { open: '10:00', close: '20:00' },
      sunday: { open: '11:00', close: '18:00' },
    },
    rating: 4.4,
    review_count: 45,
    is_verified: true,
    is_claimed: true,
    owner_id: '22',
    status: 'approved',
    created_at: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // LEGAL SERVICES
  {
    id: '23',
    name: 'Mulu Law Firm',
    slug: 'mulu-law-firm',
    description: 'Seasoned attorney with over a decade of national and international legal expertise. Specializing in business & international trade laws, immigration laws, and contract negotiations.',
    category: 'legal-services',
    address: '7900 Xerxes Ave S, Suite 2500',
    city: 'Bloomington',
    state: 'MN',
    zip_code: '55431',
    phone: '(952) 555-0789',
    email: 'contact@mululawfirm.com',
    website: 'https://www.mululawfirm.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '16:00' },
      saturday: null,
      sunday: null,
    },
    rating: 4.9,
    review_count: 34,
    is_verified: true,
    is_claimed: true,
    owner_id: '23',
    status: 'approved',
    created_at: new Date(Date.now() - 250 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '24',
    name: 'AMA Law Group',
    slug: 'ama-law-group',
    description: 'Immigration law specialists. Principal attorney Abdinasir is fluent in English, Somali, and Amharic. Former Chief Justice of Somalia region Supreme Court.',
    category: 'legal-services',
    address: '1113 E Franklin Ave, Suite 104',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55404',
    phone: '(612) 444-3456',
    email: 'info@amalawgroup.com',
    website: 'https://www.amalawgroup.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '16:00' },
      saturday: null,
      sunday: null,
    },
    rating: 4.7,
    review_count: 28,
    is_verified: true,
    is_claimed: true,
    owner_id: '24',
    status: 'approved',
    created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // HEALTHCARE
  {
    id: '25',
    name: 'Inspire Change Clinic',
    slug: 'inspire-change-clinic',
    description: 'Healthcare clinic with staff speaking Somali, Spanish, and Oromo. Two doctors, nurse practitioners, and nurses on staff. Serving Ventura Village and surrounding neighborhoods.',
    category: 'health-wellness',
    address: '2520 Park Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55404',
    phone: '(612) 555-0890',
    email: 'info@inspirechangeclinic.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '08:00', close: '17:00' },
      tuesday: { open: '08:00', close: '17:00' },
      wednesday: { open: '08:00', close: '17:00' },
      thursday: { open: '08:00', close: '17:00' },
      friday: { open: '08:00', close: '16:00' },
      saturday: { open: '09:00', close: '13:00' },
      sunday: null,
    },
    rating: 4.8,
    review_count: 56,
    is_verified: true,
    is_claimed: true,
    owner_id: '25',
    status: 'approved',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '26',
    name: 'Gargar Urgent Care & Clinic',
    slug: 'gargar-urgent-care',
    description: 'Urgent care and primary care services. Culturally sensitive healthcare for the East African community. Walk-ins welcome.',
    category: 'health-wellness',
    address: '2925 Chicago Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55407',
    phone: '(612) 555-0567',
    email: 'info@gargarcare.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '08:00', close: '20:00' },
      tuesday: { open: '08:00', close: '20:00' },
      wednesday: { open: '08:00', close: '20:00' },
      thursday: { open: '08:00', close: '20:00' },
      friday: { open: '08:00', close: '20:00' },
      saturday: { open: '09:00', close: '17:00' },
      sunday: { open: '10:00', close: '16:00' },
    },
    rating: 4.6,
    review_count: 89,
    is_verified: true,
    is_claimed: true,
    owner_id: '26',
    status: 'approved',
    created_at: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // REAL ESTATE
  {
    id: '27',
    name: 'Chuchu Girma Real Estate',
    slug: 'chuchu-girma-real-estate',
    description: 'Experienced Ethiopian real estate agent serving the Twin Cities. Helping families find their dream homes. First-time buyer specialist.',
    category: 'real-estate',
    address: '4500 Park Glen Rd',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55416',
    phone: '(612) 555-0345',
    email: 'chuchu@chuchurealty.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '18:00' },
      saturday: { open: '10:00', close: '16:00' },
      sunday: { open: '12:00', close: '16:00' },
    },
    rating: 4.9,
    review_count: 45,
    is_verified: true,
    is_claimed: true,
    owner_id: '27',
    status: 'approved',
    created_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '28',
    name: 'Goodir Realty',
    slug: 'goodir-realty',
    description: 'Minneapolis real estate team speaking English and Somali. Expert guidance through buying and selling processes. Serving the East African community.',
    category: 'real-estate',
    address: '3033 Excelsior Blvd',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55416',
    phone: '(612) 555-0678',
    email: 'info@goodirrealty.com',
    website: 'https://goodirrealty.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: '10:00', close: '15:00' },
      sunday: null,
    },
    rating: 4.7,
    review_count: 34,
    is_verified: true,
    is_claimed: true,
    owner_id: '28',
    status: 'approved',
    created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // FINANCIAL SERVICES
  {
    id: '29',
    name: 'African Development Center',
    slug: 'african-development-center',
    description: 'Financial success guidance for African immigrants in America. Business development, homeownership programs, and financial literacy. Empowering the community since 2003.',
    category: 'financial-services',
    address: '1931 S 5th St',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 333-4772',
    email: 'info@adcminnesota.org',
    website: 'https://www.adcminnesota.org/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '16:00' },
      saturday: null,
      sunday: null,
    },
    rating: 4.8,
    review_count: 67,
    is_verified: true,
    is_claimed: true,
    owner_id: '29',
    status: 'approved',
    created_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // TRANSPORTATION
  {
    id: '30',
    name: 'Omo Ola Transport LLC',
    slug: 'omo-ola-transport',
    description: 'Licensed transportation and logistics company serving Minnesota. USDOT registered and insured. Reliable service for the community.',
    category: 'automotive',
    address: '2500 E Lake St',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55406',
    phone: '(612) 555-0912',
    email: 'dispatch@omoolatransport.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '06:00', close: '22:00' },
      tuesday: { open: '06:00', close: '22:00' },
      wednesday: { open: '06:00', close: '22:00' },
      thursday: { open: '06:00', close: '22:00' },
      friday: { open: '06:00', close: '22:00' },
      saturday: { open: '07:00', close: '20:00' },
      sunday: { open: '08:00', close: '18:00' },
    },
    rating: 4.5,
    review_count: 34,
    is_verified: true,
    is_claimed: true,
    owner_id: '30',
    status: 'approved',
    created_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // MORE RESTAURANTS
  {
    id: '31',
    name: 'Lulu Ethiovegan',
    slug: 'lulu-ethiovegan',
    description: 'Vegan versions of traditional Ethiopian recipes. Located just off Nicollet and Franklin. Plant-based Ethiopian cuisine for conscious eaters.',
    category: 'restaurant-food',
    address: '1900 Nicollet Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55403',
    phone: '(612) 555-0234',
    email: 'hello@luluethiovegan.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '21:00' },
      tuesday: { open: '11:00', close: '21:00' },
      wednesday: { open: '11:00', close: '21:00' },
      thursday: { open: '11:00', close: '21:00' },
      friday: { open: '11:00', close: '22:00' },
      saturday: { open: '11:00', close: '22:00' },
      sunday: { open: '12:00', close: '20:00' },
    },
    rating: 4.7,
    review_count: 89,
    is_verified: true,
    is_claimed: true,
    owner_id: '31',
    status: 'approved',
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '32',
    name: 'Baarakallah Restaurant',
    slug: 'baarakallah-restaurant',
    description: 'Friendly service and large portions of East African dishes. Located in Cedar-Riverside. Authentic flavors and welcoming atmosphere.',
    category: 'restaurant-food',
    address: '419 Cedar Ave S',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 555-0345',
    email: 'info@baarakallah.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '10:00', close: '22:00' },
      tuesday: { open: '10:00', close: '22:00' },
      wednesday: { open: '10:00', close: '22:00' },
      thursday: { open: '10:00', close: '22:00' },
      friday: { open: '10:00', close: '23:00' },
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    rating: 4.4,
    review_count: 67,
    is_verified: true,
    is_claimed: true,
    owner_id: '32',
    status: 'approved',
    created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '33',
    name: 'Tamu Grill',
    slug: 'tamu-grill',
    description: 'Bringing the tastes of Kenya to Minneapolis. Accommodates food sensitivities like nuts, eggs, or dairy without sacrificing flavor. Cedar-Riverside location.',
    category: 'restaurant-food',
    address: '425 Cedar Ave S',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 555-0456',
    email: 'info@tamugrill.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '21:00' },
      tuesday: { open: '11:00', close: '21:00' },
      wednesday: { open: '11:00', close: '21:00' },
      thursday: { open: '11:00', close: '21:00' },
      friday: { open: '11:00', close: '22:00' },
      saturday: { open: '11:00', close: '22:00' },
      sunday: { open: '11:00', close: '21:00' },
    },
    rating: 4.5,
    review_count: 78,
    is_verified: true,
    is_claimed: true,
    owner_id: '33',
    status: 'approved',
    created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '34',
    name: 'Kilimanjaro Cafe',
    slug: 'kilimanjaro-cafe',
    description: 'Serving people from all over Africa since 1999. Owned by Abraham Kahsay from Eritrea. A Cedar-Riverside institution for East African cuisine.',
    category: 'restaurant-food',
    address: '430 Cedar Ave S',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 555-0567',
    email: 'info@kilimanjarocafe.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '10:00', close: '21:00' },
      tuesday: { open: '10:00', close: '21:00' },
      wednesday: { open: '10:00', close: '21:00' },
      thursday: { open: '10:00', close: '21:00' },
      friday: { open: '10:00', close: '22:00' },
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '21:00' },
    },
    rating: 4.3,
    review_count: 145,
    is_verified: true,
    is_claimed: true,
    owner_id: '34',
    status: 'approved',
    created_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // MORE MARKETS & GROCERY
  {
    id: '35',
    name: 'Wadajir Grocery & Halal Meat',
    slug: 'wadajir-grocery',
    description: 'Family owned East African grocery with traditional specialties. Herbs and spices including berbere, tikur azmud (Ethiopian cumin), and koraima (cardamom).',
    category: 'grocery-market',
    address: '525 Cedar Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 555-0678',
    email: 'info@wadijirgrocery.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '08:00', close: '21:00' },
      tuesday: { open: '08:00', close: '21:00' },
      wednesday: { open: '08:00', close: '21:00' },
      thursday: { open: '08:00', close: '21:00' },
      friday: { open: '08:00', close: '22:00' },
      saturday: { open: '08:00', close: '22:00' },
      sunday: { open: '09:00', close: '20:00' },
    },
    rating: 4.5,
    review_count: 89,
    is_verified: true,
    is_claimed: true,
    owner_id: '35',
    status: 'approved',
    created_at: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '36',
    name: 'Addis Market',
    slug: 'addis-market',
    description: 'Go-to spot for Ethiopian products. Wide range of spices, food items, and various goods. Ethiopian coffee, prepared injera, and wheat loaves available.',
    category: 'grocery-market',
    address: '2900 Chicago Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55407',
    phone: '(612) 555-0789',
    email: 'info@addismarket.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '20:00' },
      tuesday: { open: '09:00', close: '20:00' },
      wednesday: { open: '09:00', close: '20:00' },
      thursday: { open: '09:00', close: '20:00' },
      friday: { open: '09:00', close: '21:00' },
      saturday: { open: '09:00', close: '21:00' },
      sunday: { open: '10:00', close: '19:00' },
    },
    rating: 4.6,
    review_count: 67,
    is_verified: true,
    is_claimed: true,
    owner_id: '36',
    status: 'approved',
    created_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // EDUCATION
  {
    id: '37',
    name: 'Qubee Learning Center',
    slug: 'qubee-learning-center',
    description: 'After-school tutoring and Afaan Oromoo language classes for children and adults. Preserving language and culture for the next generation.',
    category: 'education-tutoring',
    address: '4567 Cedar Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55407',
    phone: '(612) 555-0135',
    email: 'learn@qubeelearning.org',
    website: 'https://qubeelearning.org/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '15:00', close: '20:00' },
      tuesday: { open: '15:00', close: '20:00' },
      wednesday: { open: '15:00', close: '20:00' },
      thursday: { open: '15:00', close: '20:00' },
      friday: { open: '15:00', close: '19:00' },
      saturday: { open: '09:00', close: '15:00' },
      sunday: null,
    },
    rating: 4.9,
    review_count: 78,
    is_verified: true,
    is_claimed: true,
    owner_id: '37',
    status: 'approved',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // MORE PROFESSIONAL SERVICES
  {
    id: '38',
    name: 'International Oromo Lawyers Association',
    slug: 'iola',
    description: 'Non-profit professional association pursuing liberty and justice through the legal profession. Providing referrals to Oromo attorneys nationwide.',
    category: 'legal-services',
    address: '123 Main St',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55401',
    phone: '(612) 555-0246',
    email: 'info@oromolawyers.org',
    website: 'https://www.oromolawyers.org/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '16:00' },
      saturday: null,
      sunday: null,
    },
    rating: 4.8,
    review_count: 23,
    is_verified: true,
    is_claimed: true,
    owner_id: '38',
    status: 'approved',
    created_at: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '39',
    name: 'International Oromo Health Professionals Association',
    slug: 'iohpa-minnesota',
    description: 'Improving healthcare services for Oromo and East African communities. COVID-19 vaccination events, diabetes and blood pressure screenings at community centers.',
    category: 'health-wellness',
    address: '1821 University Ave W',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55104',
    phone: '(651) 555-0357',
    email: 'info@iohpa.org',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '16:00' },
      saturday: null,
      sunday: null,
    },
    rating: 4.9,
    review_count: 34,
    is_verified: true,
    is_claimed: true,
    owner_id: '39',
    status: 'approved',
    created_at: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // MALLS & SHOPPING CENTERS
  {
    id: '40',
    name: 'African International Mall',
    slug: 'african-international-mall',
    description: 'Business owners selling clothing, fabric, jewelry, treats, drycleaning, tailoring, travel services, tax help, and henna art. Located behind Riverside Plaza.',
    category: 'retail-shopping',
    address: '619 6th St S',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 555-0468',
    email: 'info@africanmall.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '10:00', close: '20:00' },
      tuesday: { open: '10:00', close: '20:00' },
      wednesday: { open: '10:00', close: '20:00' },
      thursday: { open: '10:00', close: '20:00' },
      friday: { open: '10:00', close: '21:00' },
      saturday: { open: '10:00', close: '21:00' },
      sunday: { open: '11:00', close: '18:00' },
    },
    rating: 4.3,
    review_count: 123,
    is_verified: true,
    is_claimed: true,
    owner_id: '40',
    status: 'approved',
    created_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '41',
    name: 'Al-Karama Mall',
    slug: 'al-karama-mall',
    description: 'Dozens of East African business owners running small shops. Hijabs, Qurans, prayer rugs, East African and Middle Eastern household goods.',
    category: 'retail-shopping',
    address: '415 Cedar Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 555-0579',
    email: 'info@alkaramamall.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '10:00', close: '20:00' },
      tuesday: { open: '10:00', close: '20:00' },
      wednesday: { open: '10:00', close: '20:00' },
      thursday: { open: '10:00', close: '20:00' },
      friday: { open: '10:00', close: '21:00' },
      saturday: { open: '10:00', close: '21:00' },
      sunday: { open: '11:00', close: '18:00' },
    },
    rating: 4.2,
    review_count: 98,
    is_verified: true,
    is_claimed: true,
    owner_id: '41',
    status: 'approved',
    created_at: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // MORE BEAUTY
  {
    id: '42',
    name: 'Haja African Hair Braiding',
    slug: 'haja-hair-braiding',
    description: 'Professional African hair braiding services in North Minneapolis. Experienced stylists specializing in all types of braids and protective styles.',
    category: 'beauty-personal-care',
    address: '2130 N 44th Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55412',
    phone: '(612) 555-0680',
    email: 'book@hajabraiding.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '19:00' },
      saturday: { open: '09:00', close: '17:00' },
      sunday: null,
    },
    rating: 4.6,
    review_count: 67,
    is_verified: true,
    is_claimed: true,
    owner_id: '42',
    status: 'approved',
    created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '43',
    name: 'Queen Habesha Hair Braiding',
    slug: 'queen-habesha-braiding',
    description: 'Traditional and modern braiding styles. Specializing in Ethiopian and Eritrean braiding techniques. Located in Burnsville.',
    category: 'beauty-personal-care',
    address: '1234 Burnsville Center',
    city: 'Burnsville',
    state: 'MN',
    zip_code: '55306',
    phone: '(952) 555-0791',
    email: 'info@queenhabesha.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '19:00' },
      saturday: { open: '09:00', close: '17:00' },
      sunday: null,
    },
    rating: 4.7,
    review_count: 45,
    is_verified: true,
    is_claimed: true,
    owner_id: '43',
    status: 'approved',
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '44',
    name: 'Bintou Hair Braiding',
    slug: 'bintou-hair-braiding',
    description: 'Expert in goddess braids, fulani braids, and more. Professional braiding services in Minneapolis. Creating beautiful protective styles.',
    category: 'beauty-personal-care',
    address: '2800 Lyndale Ave S',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55408',
    phone: '(612) 555-0802',
    email: 'book@bintouhairbraidingmn.com',
    website: 'https://www.bintouhairbraidingmn.com/',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '19:00' },
      saturday: { open: '09:00', close: '17:00' },
      sunday: null,
    },
    rating: 4.8,
    review_count: 56,
    is_verified: true,
    is_claimed: true,
    owner_id: '44',
    status: 'approved',
    created_at: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // MORE SERVICES
  {
    id: '45',
    name: 'Sisterhood Boutique',
    slug: 'sisterhood-boutique',
    description: 'Started by East African women aged 14-23 living in Cedar-Riverside. Colorful variety of clothing and accessories at affordable prices.',
    category: 'retail-shopping',
    address: '500 Cedar Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 555-0913',
    email: 'info@sisterhoodboutique.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '19:00' },
      tuesday: { open: '11:00', close: '19:00' },
      wednesday: { open: '11:00', close: '19:00' },
      thursday: { open: '11:00', close: '19:00' },
      friday: { open: '11:00', close: '20:00' },
      saturday: { open: '11:00', close: '20:00' },
      sunday: { open: '12:00', close: '17:00' },
    },
    rating: 4.5,
    review_count: 34,
    is_verified: true,
    is_claimed: true,
    owner_id: '45',
    status: 'approved',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // MONEY TRANSFER & SERVICES
  {
    id: '46',
    name: 'Dahabshiil Money Transfer',
    slug: 'dahabshiil-cedar',
    description: 'International money transfer services to East Africa. Fast and reliable remittance services for the community. Licensed and insured.',
    category: 'financial-services',
    address: '510 Cedar Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 555-1024',
    email: 'info@dahabshiilmn.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '18:00' },
      saturday: { open: '10:00', close: '16:00' },
      sunday: null,
    },
    rating: 4.4,
    review_count: 78,
    is_verified: true,
    is_claimed: true,
    owner_id: '46',
    status: 'approved',
    created_at: new Date(Date.now() - 250 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // TRAVEL SERVICES
  {
    id: '47',
    name: 'Horn of Africa Travel',
    slug: 'horn-africa-travel',
    description: 'Travel agency specializing in flights to Ethiopia, Kenya, Somalia, and Djibouti. Visa assistance and tour packages available.',
    category: 'professional-services',
    address: '420 Cedar Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55454',
    phone: '(612) 555-1135',
    email: 'book@hornafricatravel.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: '10:00', close: '15:00' },
      sunday: null,
    },
    rating: 4.6,
    review_count: 56,
    is_verified: true,
    is_claimed: true,
    owner_id: '47',
    status: 'approved',
    created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // TECHNOLOGY
  {
    id: '48',
    name: 'Oromia Tech Solutions',
    slug: 'oromia-tech-solutions',
    description: 'IT services and computer repair for businesses and individuals. Web development, network setup, and tech support. Serving the Twin Cities.',
    category: 'technology-it',
    address: '3500 Nicollet Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55408',
    phone: '(612) 555-1246',
    email: 'support@oromiatech.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: '10:00', close: '14:00' },
      sunday: null,
    },
    rating: 4.7,
    review_count: 34,
    is_verified: true,
    is_claimed: true,
    owner_id: '48',
    status: 'approved',
    created_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // EVENTS & ENTERTAINMENT
  {
    id: '49',
    name: 'Irreecha Events & Catering',
    slug: 'irreecha-events',
    description: 'Event planning and catering for Oromo cultural celebrations, weddings, graduations, and community gatherings. Traditional and modern event services.',
    category: 'entertainment-events',
    address: '2100 E Lake St',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55407',
    phone: '(612) 555-1357',
    email: 'events@irreechacatering.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: '09:00', close: '17:00' },
      sunday: { open: '09:00', close: '17:00' },
    },
    rating: 4.8,
    review_count: 45,
    is_verified: true,
    is_claimed: true,
    owner_id: '49',
    status: 'approved',
    created_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // TAX SERVICES
  {
    id: '50',
    name: 'Oromia Tax & Accounting',
    slug: 'oromia-tax-accounting',
    description: 'Tax preparation and bookkeeping services for individuals and small businesses. Bilingual services available in English and Oromo.',
    category: 'financial-services',
    address: '1850 University Ave W',
    city: 'Saint Paul',
    state: 'MN',
    zip_code: '55104',
    phone: '(651) 555-1468',
    email: 'taxes@oromiatax.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: '10:00', close: '14:00' },
      sunday: null,
    },
    rating: 4.7,
    review_count: 56,
    is_verified: true,
    is_claimed: true,
    owner_id: '50',
    status: 'approved',
    created_at: new Date(Date.now() - 250 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export default function BusinessesPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1">
        <BusinessFilters businesses={realBusinesses} />

        {/* Add Business CTA */}
        <section className="py-12 bg-gradient-to-r from-emerald-600 to-teal-600">
          <div className="mx-auto max-w-7xl px-4 text-center">
            <h2 className="text-2xl md:text-3xl font-bold text-white mb-4">
              Own an Oromo Business?
            </h2>
            <p className="text-emerald-100 mb-6 max-w-2xl mx-auto">
              List your business for free and connect with the Oromo community.
              Get discovered by customers looking to support Oromo-owned businesses.
            </p>
            <Button size="lg" variant="secondary" asChild>
              <Link href="/businesses/add">
                <Plus className="w-5 h-5 mr-2" />
                Add Your Business
              </Link>
            </Button>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  )
}
