import Link from 'next/link'
import { Plus } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Header } from '@/components/layout/header'
import { Footer } from '@/components/layout/footer'
import { BusinessFilters } from '@/components/businesses/business-filters'
import { Business } from '@/types/business'

// Mock data - 15 sample businesses across different cities
const mockBusinesses: Business[] = [
  {
    id: '1',
    name: 'Oromia Restaurant',
    slug: 'oromia-restaurant',
    description: 'Authentic Oromo cuisine featuring traditional dishes like kitfo, tibs, and injera. Family-owned since 2010.',
    category: 'restaurant',
    address: '1234 Lake Street',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55407',
    phone: '(612) 555-0123',
    email: 'info@oromiarestaurant.com',
    website: 'https://oromiarestaurant.com',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '22:00' },
      tuesday: { open: '11:00', close: '22:00' },
      wednesday: { open: '11:00', close: '22:00' },
      thursday: { open: '11:00', close: '22:00' },
      friday: { open: '11:00', close: '23:00' },
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '10:00', close: '21:00' },
    },
    rating: 4.8,
    review_count: 127,
    is_verified: true,
    is_claimed: true,
    owner_id: '1',
    status: 'approved',
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Buna Coffee House',
    slug: 'buna-coffee-house',
    description: 'Traditional Ethiopian coffee ceremony and pastries. The perfect spot for authentic buna experience.',
    category: 'restaurant',
    address: '5678 Central Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55418',
    phone: '(612) 555-0456',
    email: 'hello@bunacoffee.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '07:00', close: '20:00' },
      tuesday: { open: '07:00', close: '20:00' },
      wednesday: { open: '07:00', close: '20:00' },
      thursday: { open: '07:00', close: '20:00' },
      friday: { open: '07:00', close: '21:00' },
      saturday: { open: '08:00', close: '21:00' },
      sunday: { open: '08:00', close: '18:00' },
    },
    rating: 4.6,
    review_count: 89,
    is_verified: true,
    is_claimed: true,
    owner_id: '2',
    status: 'approved',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Oromo Market & Grocery',
    slug: 'oromo-market-grocery',
    description: 'Your one-stop shop for East African groceries, spices, and specialty items. Fresh injera baked daily.',
    category: 'grocery',
    address: '9012 Georgia Ave',
    city: 'Washington',
    state: 'DC',
    zip_code: '20011',
    phone: '(202) 555-0789',
    email: 'shop@oromomarket.com',
    website: 'https://oromomarket.com',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '08:00', close: '21:00' },
      tuesday: { open: '08:00', close: '21:00' },
      wednesday: { open: '08:00', close: '21:00' },
      thursday: { open: '08:00', close: '21:00' },
      friday: { open: '08:00', close: '21:00' },
      saturday: { open: '08:00', close: '22:00' },
      sunday: { open: '09:00', close: '20:00' },
    },
    rating: 4.5,
    review_count: 156,
    is_verified: true,
    is_claimed: true,
    owner_id: '3',
    status: 'approved',
    created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Gadaa Legal Services',
    slug: 'gadaa-legal-services',
    description: 'Immigration and family law specialists serving the Oromo community. Bilingual attorneys available.',
    category: 'professional',
    address: '3456 K Street NW',
    city: 'Washington',
    state: 'DC',
    zip_code: '20007',
    phone: '(202) 555-0321',
    email: 'contact@gadaalegal.com',
    website: 'https://gadaalegal.com',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '16:00' },
      saturday: null,
      sunday: null,
    },
    rating: 4.9,
    review_count: 45,
    is_verified: true,
    is_claimed: true,
    owner_id: '4',
    status: 'approved',
    created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Harar Beauty Salon',
    slug: 'harar-beauty-salon',
    description: 'Full-service salon specializing in African hair care, braiding, and beauty treatments.',
    category: 'beauty',
    address: '7890 Rainier Ave S',
    city: 'Seattle',
    state: 'WA',
    zip_code: '98118',
    phone: '(206) 555-0654',
    email: 'appointments@hararbeauty.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '10:00', close: '19:00' },
      tuesday: { open: '10:00', close: '19:00' },
      wednesday: { open: '10:00', close: '19:00' },
      thursday: { open: '10:00', close: '19:00' },
      friday: { open: '10:00', close: '20:00' },
      saturday: { open: '09:00', close: '18:00' },
      sunday: null,
    },
    rating: 4.7,
    review_count: 98,
    is_verified: true,
    is_claimed: true,
    owner_id: '5',
    status: 'approved',
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Oromia Auto Repair',
    slug: 'oromia-auto-repair',
    description: 'Honest and reliable auto repair services. Specializing in domestic and import vehicles.',
    category: 'auto',
    address: '2468 Buford Highway',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30329',
    phone: '(404) 555-0987',
    email: 'service@oromiauto.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '09:00', close: '14:00' },
      sunday: null,
    },
    rating: 4.4,
    review_count: 67,
    is_verified: false,
    is_claimed: true,
    owner_id: '6',
    status: 'approved',
    created_at: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Abbaa Realty Group',
    slug: 'abbaa-realty-group',
    description: 'Helping families find their dream homes. First-time buyer specialists with community focus.',
    category: 'real-estate',
    address: '1357 Harry Hines Blvd',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75235',
    phone: '(214) 555-0246',
    email: 'homes@abbaarealty.com',
    website: 'https://abbaarealty.com',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '18:00' },
      saturday: { open: '10:00', close: '16:00' },
      sunday: { open: '12:00', close: '16:00' },
    },
    rating: 4.8,
    review_count: 34,
    is_verified: true,
    is_claimed: true,
    owner_id: '7',
    status: 'approved',
    created_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Qubee Learning Center',
    slug: 'qubee-learning-center',
    description: 'After-school tutoring and Afaan Oromoo language classes for children and adults.',
    category: 'education',
    address: '4567 Cedar Ave',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55407',
    phone: '(612) 555-0135',
    email: 'learn@qubeelearning.org',
    website: 'https://qubeelearning.org',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '15:00', close: '20:00' },
      tuesday: { open: '15:00', close: '20:00' },
      wednesday: { open: '15:00', close: '20:00' },
      thursday: { open: '15:00', close: '20:00' },
      friday: { open: '15:00', close: '19:00' },
      saturday: { open: '09:00', close: '15:00' },
      sunday: null,
    },
    rating: 4.9,
    review_count: 78,
    is_verified: true,
    is_claimed: true,
    owner_id: '8',
    status: 'approved',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Finfinnee Clinic',
    slug: 'finfinnee-clinic',
    description: 'Family medicine and primary care with Oromo-speaking providers. Accepting new patients.',
    category: 'healthcare',
    address: '8901 Columbia Pike',
    city: 'Washington',
    state: 'DC',
    zip_code: '22204',
    phone: '(703) 555-0468',
    email: 'appointments@finfinneeclinic.com',
    website: 'https://finfinneeclinic.com',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '08:00', close: '17:00' },
      tuesday: { open: '08:00', close: '17:00' },
      wednesday: { open: '08:00', close: '17:00' },
      thursday: { open: '08:00', close: '17:00' },
      friday: { open: '08:00', close: '16:00' },
      saturday: { open: '09:00', close: '13:00' },
      sunday: null,
    },
    rating: 4.6,
    review_count: 112,
    is_verified: true,
    is_claimed: true,
    owner_id: '9',
    status: 'approved',
    created_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Aannoo Fashion',
    slug: 'aannoo-fashion',
    description: 'Traditional Oromo clothing and modern African fashion. Custom tailoring available.',
    category: 'clothing',
    address: '3579 MLK Jr Way',
    city: 'Seattle',
    state: 'WA',
    zip_code: '98144',
    phone: '(206) 555-0792',
    email: 'style@aannoofashion.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '10:00', close: '18:00' },
      tuesday: { open: '10:00', close: '18:00' },
      wednesday: { open: '10:00', close: '18:00' },
      thursday: { open: '10:00', close: '18:00' },
      friday: { open: '10:00', close: '19:00' },
      saturday: { open: '10:00', close: '19:00' },
      sunday: { open: '12:00', close: '17:00' },
    },
    rating: 4.5,
    review_count: 43,
    is_verified: false,
    is_claimed: true,
    owner_id: '10',
    status: 'approved',
    created_at: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Dire Dawa Grill',
    slug: 'dire-dawa-grill',
    description: 'Grilled meats and traditional stews in a family-friendly atmosphere. Catering available.',
    category: 'restaurant',
    address: '2468 Clairmont Road',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30329',
    phone: '(404) 555-0159',
    email: 'eat@diredawagrill.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '11:00', close: '21:00' },
      tuesday: { open: '11:00', close: '21:00' },
      wednesday: { open: '11:00', close: '21:00' },
      thursday: { open: '11:00', close: '21:00' },
      friday: { open: '11:00', close: '22:00' },
      saturday: { open: '11:00', close: '22:00' },
      sunday: { open: '12:00', close: '20:00' },
    },
    rating: 4.3,
    review_count: 89,
    is_verified: true,
    is_claimed: true,
    owner_id: '11',
    status: 'approved',
    created_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Oromia Tax & Accounting',
    slug: 'oromia-tax-accounting',
    description: 'Tax preparation and bookkeeping services for individuals and small businesses.',
    category: 'professional',
    address: '1593 Forest Lane',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75234',
    phone: '(214) 555-0357',
    email: 'taxes@oromiatax.com',
    website: 'https://oromiatax.com',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: '10:00', close: '14:00' },
      sunday: null,
    },
    rating: 4.7,
    review_count: 56,
    is_verified: true,
    is_claimed: true,
    owner_id: '12',
    status: 'approved',
    created_at: new Date(Date.now() - 250 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'Booranaa Spice Shop',
    slug: 'booranaa-spice-shop',
    description: 'Authentic Ethiopian spices, berbere, mitmita, and specialty ingredients.',
    category: 'grocery',
    address: '7531 International Blvd',
    city: 'Seattle',
    state: 'WA',
    zip_code: '98108',
    phone: '(206) 555-0864',
    email: 'spices@booranaa.com',
    website: null,
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '19:00' },
      tuesday: { open: '09:00', close: '19:00' },
      wednesday: { open: '09:00', close: '19:00' },
      thursday: { open: '09:00', close: '19:00' },
      friday: { open: '09:00', close: '20:00' },
      saturday: { open: '09:00', close: '20:00' },
      sunday: { open: '10:00', close: '18:00' },
    },
    rating: 4.8,
    review_count: 124,
    is_verified: true,
    is_claimed: true,
    owner_id: '13',
    status: 'approved',
    created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '14',
    name: 'Waaqeffannaa Wellness',
    slug: 'waaqeffannaa-wellness',
    description: 'Holistic health services including massage therapy, acupuncture, and wellness coaching.',
    category: 'healthcare',
    address: '9513 Peachtree Street',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30309',
    phone: '(404) 555-0753',
    email: 'wellness@waaqeffannaa.com',
    website: 'https://waaqeffannaa.com',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '10:00', close: '19:00' },
      tuesday: { open: '10:00', close: '19:00' },
      wednesday: { open: '10:00', close: '19:00' },
      thursday: { open: '10:00', close: '19:00' },
      friday: { open: '10:00', close: '18:00' },
      saturday: { open: '09:00', close: '16:00' },
      sunday: null,
    },
    rating: 4.9,
    review_count: 38,
    is_verified: true,
    is_claimed: true,
    owner_id: '14',
    status: 'approved',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '15',
    name: 'Gada Insurance Agency',
    slug: 'gada-insurance-agency',
    description: 'Auto, home, and life insurance with personalized service. Free quotes available.',
    category: 'professional',
    address: '3691 Belt Line Road',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75001',
    phone: '(214) 555-0951',
    email: 'quote@gadainsurance.com',
    website: 'https://gadainsurance.com',
    logo_url: null,
    cover_image_url: null,
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '16:00' },
      saturday: null,
      sunday: null,
    },
    rating: 4.6,
    review_count: 29,
    is_verified: true,
    is_claimed: true,
    owner_id: '15',
    status: 'approved',
    created_at: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export default function BusinessesPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1">
        <BusinessFilters businesses={mockBusinesses} />

        {/* Add Business CTA */}
        <section className="py-12 bg-gradient-to-r from-emerald-600 to-teal-600">
          <div className="mx-auto max-w-7xl px-4 text-center">
            <h2 className="text-2xl md:text-3xl font-bold text-white mb-4">
              Own an Oromo Business?
            </h2>
            <p className="text-emerald-100 mb-6 max-w-2xl mx-auto">
              List your business for free and connect with the Oromo community.
              Get discovered by customers looking to support Oromo-owned businesses.
            </p>
            <Button size="lg" variant="secondary" asChild>
              <Link href="/businesses/add">
                <Plus className="w-5 h-5 mr-2" />
                Add Your Business
              </Link>
            </Button>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  )
}
